spring:
  application:
    name: chucked
  profiles:
    active: local
    group:
      local:
        - file
        - secret

  datasource:
    url: jdbc:mysql://localhost:3306/s3example
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ON_SECRET
    password: ON_SECRET

  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQLDialect

cloud:
  aws:
    s3:
      bucket: ON_SECRET
    credentials:
      access-key: ON_SECRET
      secret-key: ON_SECRET
    region:
      static: ON_SECRET
      auto: false
    stack:
      auto: false

springdoc:
  use-fqn: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    path: /api-docs
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /api-docs
    disable-swagger-default-url: true
    doc-expansion: none
  paths-to-match:
    - /**